<a href="https://colab.research.google.com/github/lakshyamodi832/ml/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
mean = np.mean(x)
print(mean)
y = np.zeros([2,3])
print(y)
z = np.identity(2)
print(z)

3.5
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
a = np.ones(5)
b = np.arange(1, 6, 2)
c = np.linspace(1, 5, 10)
print(a, b, c)

[1. 1. 1. 1. 1.] [1 3 5] [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
y_shae = y.shape
y_shae

(2, 3)

In [ ]:
print(y.shape)
y = y.reshape(3, 2)
y

(2, 3)


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
print(x[1])

[4 5 6]


In [ ]:
l = np.array([1, 2])
m = np.array([3, 4])
xCon = np.append(l, 5)
xCon

array([1, 2, 5])